# Generated by Django 2.0.9 on 2018-12-29 19:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='finish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
