# Generated by Django 2.0.9 on 2018-12-30 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20181230_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='finish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
